name: Website

on:
  push:
    branches: [website]
  workflow_dispatch: {}

concurrency:
  group: website-${{ github.ref }}
  cancel-in-progress: true

jobs:

  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm config set registry ${{ vars.NPM_CI_REGISTRY }}
        if: ${{ vars.NPM_CI_REGISTRY }}
      - run: |
          npm ci
          npm run gh-pages
