name: Website

on:
  push:
    branches: [website]
  workflow_dispatch: {}

concurrency:
  group: website-${{ github.ref }}
  cancel-in-progress: true

jobs:

  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: actions/checkout@v4
        with:
          path: website
          ref: website
      - uses: actions/checkout@v4
        with:
          path: gh-pages
          ref: gh-pages
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: |
          npm ci
          cd website && npm ci && cd ..
          npm run gh-pages
