name: Website

on:
  push:
    branches: [website]
  workflow_dispatch: {}

concurrency:
  group: website-${{ github.ref }}
  cancel-in-progress: true

jobs:

  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - run: npm ci --omit=dev
      - uses: actions/checkout@v4
        with:
          path: website
          ref: website
      - run: |
          cd website
          npm ci
      - uses: actions/cache@v2
        with:
          path: 'website/node_modules/.cache'
          key: build-cache
      - uses: actions/checkout@v4
        with:
          path: gh-pages
          ref: gh-pages
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: |
          git config --global user.email "git@cha0s.io"
          git config --global user.name "cha0s"
          npm run gh-pages
